# Generated by Django 5.0.7 on 2024-07-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch_cities', '0001_initial'),
        ('car_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats', models.IntegerField()),
                ('pricing_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('description', models.TextField(max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('pick_up_date', models.DateTimeField(blank=True, null=True)),
                ('drop_off_date', models.DateTimeField(blank=True, null=True)),
                ('airconditions', models.BooleanField(default=False)),
                ('child_seat', models.BooleanField(default=False)),
                ('luggage', models.BooleanField(default=False)),
                ('music', models.BooleanField(default=False)),
                ('seat_beat', models.BooleanField(default=False)),
                ('sleeping_bed', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('onboard_computer', models.BooleanField(default=False)),
                ('audio_input', models.BooleanField(default=False)),
                ('long_term_trips', models.BooleanField(default=False)),
                ('car_kit', models.BooleanField(default=False)),
                ('remote_central_locking', models.BooleanField(default=False)),
                ('climate_control', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_category.brand')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_category.fuel')),
                ('location_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch_cities.branchcities')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_category.transmissiontype')),
            ],
        ),
        migrations.CreateModel(
            name='CarComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('starts_comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.rating')),
            ],
        ),
    ]
