# Generated by Django 5.0.7 on 2024-07-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='location_city',
            new_name='location',
        ),
    ]
