# Generated by Django 5.0.7 on 2024-07-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchcities',
            name='name_city',
            field=models.CharField(max_length=20),
        ),
    ]
